apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firecrawl-api
  template:
    metadata:
      labels:
        app: firecrawl-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.firecrawl_api.image.repository }}:{{ .Values.firecrawl_api.image.tag }}"
          imagePullPolicy: {{ .Values.firecrawl_api.image.pullPolicy }}
          args: [ "pnpm", "run", "start:production" ]
          ports:
            - containerPort: {{ .Values.firecrawl_api.service.port }}
          env:
            - name: FLY_PROCESS_GROUP
              value: "app"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          livenessProbe:
            httpGet:
              path: /v0/health/liveness
              port: {{ .Values.firecrawl_api.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v0/health/readiness
              port: {{ .Values.firecrawl_api.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: firecrawl-api
  ports:
    - protocol: TCP
      port: {{ .Values.firecrawl_api.service.port }}
      targetPort: {{ .Values.firecrawl_api.service.port }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: firecrawl-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-api
  minReplicas: {{ .Values.firecrawl_api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.firecrawl_api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
